Make sample names header-like, FIX #140
nf-core/rnasplice pull request #141
Opened 2024-05-31 14:41 UTC by fhausmann

## Description of changes

The DRIMSEQ filtering pipeline is not running, when sample names contain special characters, due to automatic conversion. This automatic conversion is now applied also to the sample names.

## PR checklist

- [X] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/rnasplice/tree/master/.github/CONTRIBUTING.md)
- [X] If necessary, also make a PR on the nf-core/rnasplice _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [X] Make sure your code lints (`nf-core lint`).
- [X] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [X] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [X] Usage Documentation in `docs/usage.md` is updated.
- [X] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [X] `README.md` is updated (including new tool citations and authors/contributors).

2026-03-05 19:17 UTC, lpantano commented
@fhausmann do you want to update this to see if tests get triggered and we can merge?

2026-03-08 11:07 UTC, fhausmann commented
@lpantano I'm happy to update/work on this more if needed. However, I'm not sure what kind of update is required. As far as I can see, there are no merge conflicts. What updates are required?

2026-06-03 19:36 UTC, piplus2 requested changes
I think a validation of the sample IDs is more robust and future proof than modifying them at runtime.

2026-06-05 07:10 UTC, fhausmann commented
> I think a validation of the sample IDs is more robust and future proof than modifying them at runtime.

 I've added checks in the shema to detect such issues as early as possible (to the best of my knowledge). Would it be acceptable to keep the `make.names` call since other R functions are doing it automatically, i.e., when calling read_csv, or should I remove it?

2026-06-08 07:21 UTC, piplus2 commented
I think that it's risky to modify the sample id at runtime in only one process because it breaks the consistency and it's a possible cause of future issues that then must be tracked down to this.
I'd suggest to instead work on the validation of the sample IDs and stop the pipeline when incompatible characters are detected, giving a feedback to the user.

2026-06-08 07:22 UTC, piplus2 commented
so please just remove the make.names call which then becomes unnecessary. Also, please check that all CIs pass. Thanks!

2026-06-08 07:38 UTC, fhausmann commented
> so please just remove the make.names call which then becomes unnecessary. Also, please check that all CIs pass. Thanks!

Thanks for your feedback. The line is removed and the changelog updated. The CI's only run upon maintainer approval, as far as I can see. If there is any issue, I'm happy to fix that.

2026-06-08 09:57 UTC, piplus2 commented
Thanks! Please check the failing CI actions. After fixing that, we can merge.

2026-06-08 10:36 UTC, fhausmann commented
Formatting is fixed. `Nextflow lint`is still failing for me locally, but only on files I didn't touch.

2026-06-08 10:44 UTC, piplus2 requested changes

2026-06-08 10:44 UTC, piplus2 commented on assets/schema_input.json
> +                    "enum": [
the enum must be on a single line. Run `prek -a` to check if there's still issues.

2026-06-08 10:57 UTC, fhausmann commented on assets/schema_input.json
> +                    "enum": [
`prek -a` gives me no issues with the current version. However, when format it to a single line, it fails with: 
```
-                    "enum": ["if", "else", "repeat", "while", "function", "for", "in", "next", "break", "TRUE", "FALSE", "NULL", "Inf", "NaN", "NA", "NA_integer_", "NA_real_", "NA_complex_", "NA_character_", "...", "..1", "..2", "..3", "..4", "..5", "..6", "..7", "..8", "..9"]
+                    "enum": [
+                        "if",
+                        "else",
+                        "repeat",
+                        "while",
+                        "function",
+                        "for",
+                        "in",
+                        "next",
+                        "break",
```
Also the diff here shows the multiline version: https://github.com/nf-core/rnasplice/actions/runs/27122522772/job/80067916430

Sure, that I should format on a single line?

2026-06-08 11:26 UTC, piplus2 commented on assets/schema_input.json
> +                    "enum": [
yes, sorry, you're right. It should pass the tests now.

2026-06-08 12:36 UTC, piplus2 approved these changes
LGTM!

2026-06-08 13:47 UTC, merged